
# Template config, need to change dump_dir, data.root_dir and data.tokenizer.path

# dump_dir: !!CHANGETHIS!!
name: "7B_pkplus_1024"
steps: 128_000
probe_freq: null
seed: 777
optim:
    lr: 1e-4
    warmup: 4000
    lr_min_ratio: 0.01
    clip: 1.0
    scheduler: linear
    annealing_step: 10000

distributed:
    fsdp_type: full_shard
    compile: false
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    checkpoint_each_layer: true
    tp_size: 1
    memory_parallel_size: 8

model:
    dim: 4096
    n_layers: 32
    n_heads: 32
    rope_theta: 100_000
    ffn_dim_multiplier: 1.0
    multiple_of: 256
    productkey_args:
        is_enabled: True
        layers:  "4,12,20"
        mem_share_values: True
        mem_n_keys: 1024
        value_fixed_lr: 0.001
        swilu_projection: True
        mem_k_dim: 512
        mem_heads: 4
        mem_knn: 32
        mem_gated: False
        mem_v_dim: -1
        peer_variant: False

data:
    root_dir: data/shuffled
    sources:
        dclm_baseline_1.0: 1.0
    batch_size: 2
    prefetch_size: 64
    seq_len: 4096
    n_views: 2
    load_async: true
    tokenizer:
        name: sp # for SentencePiece
        # path::  !!CHANGETHIS!!

profiling:
    run: true

checkpoint:
    dump:
        every: 10000
        keep: 1
    eval:
        every: 128_000
        keep: 1

logging:
    freq: 10

eval:
    generator:
        max_tokens: 8192
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - hellaswag
            - piqa
            - task: nq_open
              num_fewshot: 5
